### ISSUE TITLE
Request for more data.

### ISSUE THREAD

**Issue by XiongChen-SYSU** [Wittelab/pancancer_pleiotropy#2]
The article is brilliant and data are easy to assess. But I noticed that eaf and se of OR is missing. Especially se is very important for many analysis. Appreciate that if the author can update data with se.

**Comment by taylorcavazos** [comment]
Sorry for the late reply. Please see this resource for computing the SE from the available data: https://github.com/Wittelab/pancancer_pleiotropy/issues/1#issuecomment-776086292

**Comment by taylorcavazos** [comment]
Issue was addressed previously.
